config/routes.rb
Moneymanager::Application.routes.draw do
  resources :expenses

  resources :payment_methods

  resources :beneficiaries

  resources :categories

  

end

app/models/beneficiary.rb
class Beneficiary < ActiveRecord::Base
	
	has_many :expenses
	before_destroy :ensure_not_referenced_by_any_expense
	
	validates :title, presence: true, uniqueness: true

	private
		# Ensure that there is no expenses referencing this beneficiary
		def ensure_not_referenced_by_any_expense
			if expenses.empty?
				return true
			else
				errors.add(:base, 'Expense present')
				return false
			end
		end

end

app/controllers/beneficiaries_controller.rb
class BeneficiariesController < ApplicationController
  before_action :set_beneficiary, only: [:show, :edit, :update, :destroy]

  # GET /beneficiaries
  # GET /beneficiaries.json
  def index
    @beneficiaries = Beneficiary.all
  end

  # GET /beneficiaries/1
  # GET /beneficiaries/1.json
  def show
  end

  # GET /beneficiaries/new
  def new
    @beneficiary = Beneficiary.new
  end

  # GET /beneficiaries/1/edit
  def edit
  end

  # POST /beneficiaries
  # POST /beneficiaries.json
  def create
    @beneficiary = Beneficiary.new(beneficiary_params)

    respond_to do |format|
      if @beneficiary.save
        format.html { redirect_to @beneficiary, notice: 'Beneficiary was successfully created.' }
        format.json { render action: 'show', status: :created, location: @beneficiary }
      else
        format.html { render action: 'new' }
        format.json { render json: @beneficiary.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /beneficiaries/1
  # PATCH/PUT /beneficiaries/1.json
  def update
    respond_to do |format|
      if @beneficiary.update(beneficiary_params)
        format.html { redirect_to @beneficiary, notice: 'Beneficiary was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @beneficiary.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /beneficiaries/1
  # DELETE /beneficiaries/1.json
  def destroy
    @beneficiary.destroy
    respond_to do |format|
      format.html { redirect_to beneficiaries_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_beneficiary
      @beneficiary = Beneficiary.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def beneficiary_params
      params.require(:beneficiary).permit(:title)
    end
end

app/helpers/beneficiaries_helper.rb
module BeneficiariesHelper
end

app/views/beneficiaries/_form.html.erb
<%= form_for(@beneficiary) do |f| %>
  <% if @beneficiary.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@beneficiary.errors.count, "error") %> prohibited this beneficiary from being saved:</h2>

      <ul>
      <% @beneficiary.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/beneficiaries/edit.html.erb
<h1>Editing beneficiary</h1>

<%= render 'form' %>

<%= link_to 'Show', @beneficiary %> |
<%= link_to 'Back', beneficiaries_path %>

app/views/beneficiaries/index.html.erb
<h1>Listing beneficiaries</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @beneficiaries.each do |beneficiary| %>
      <tr>
        <td><%= beneficiary.title %></td>
        <td><%= link_to 'Show', beneficiary %></td>
        <td><%= link_to 'Edit', edit_beneficiary_path(beneficiary) %></td>
        <td><%= link_to 'Destroy', beneficiary, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Beneficiary', new_beneficiary_path %>

app/views/beneficiaries/new.html.erb
<h1>New beneficiary</h1>

<%= render 'form' %>

<%= link_to 'Back', beneficiaries_path %>

app/views/beneficiaries/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @beneficiary.title %>
</p>

<%= link_to 'Edit', edit_beneficiary_path(@beneficiary) %> |
<%= link_to 'Back', beneficiaries_path %>