config/routes.rb
Moneymanager::Application.routes.draw do
  resources :expenses

  resources :payment_methods

  resources :beneficiaries

  resources :categories

  

end

app/controllers/expenses_controller.rb
class ExpensesController < ApplicationController
  before_action :set_expense, only: [:show, :edit, :update, :destroy]

  # GET /expenses
  # GET /expenses.json
  def index
    @expenses = Expense.all
  end

  # GET /expenses/1
  # GET /expenses/1.json
  def show
  end

  # GET /expenses/new
  def new
    @expense = Expense.new
  end

  # GET /expenses/1/edit
  def edit
  end

  # POST /expenses
  # POST /expenses.json
  def create
    @expense = Expense.new(expense_params)

    respond_to do |format|
      if @expense.save
        format.html { redirect_to @expense, notice: 'Expense was successfully created.' }
        format.json { render action: 'show', status: :created, location: @expense }
      else
        format.html { render action: 'new' }
        format.json { render json: @expense.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /expenses/1
  # PATCH/PUT /expenses/1.json
  def update
    respond_to do |format|
      if @expense.update(expense_params)
        format.html { redirect_to @expense, notice: 'Expense was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @expense.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /expenses/1
  # DELETE /expenses/1.json
  def destroy
    @expense.destroy
    respond_to do |format|
      format.html { redirect_to expenses_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_expense
      @expense = Expense.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def expense_params
      params.require(:expense).permit(:title, :buying_date, :paying_date, :category_id, :beneficiary_id, :payment_method_id, :value)
    end
end

app/helpers/expenses_helper.rb
module ExpensesHelper
end

app/views/expenses/_form.html.erb
<%= form_for(@expense) do |f| %>
  <% if @expense.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@expense.errors.count, "error") %> prohibited this expense from being saved:</h2>

      <ul>
      <% @expense.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :buying_date %><br>
    <%= f.date_select :buying_date %>
  </div>
  <div class="field">
    <%= f.label :paying_date %><br>
    <%= f.date_select :paying_date %>
  </div>
  <div class="field">
    <%= f.label :category_id %><br>
    <%= f.collection_select(:category_id, Category.all, :id, :title) %>
  </div>
  <div class="field">
    <%= f.label :beneficiary_id %><br>
    <%= f.collection_select(:beneficiary_id, Beneficiary.all, :id, :title) %>
  </div>
  <div class="field">
    <%= f.label :payment_method_id %><br>
    <%= f.collection_select(:payment_method_id, PaymentMethod.all, :id, :title) %>
  </div>
  <div class="field">
  	<%= f.label :value%> in cents<br>
  	<%= f.text_field :value %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/expenses/edit.html.erb
<h1>Editing expense</h1>

<%= render 'form' %>

<%= link_to 'Show', @expense %> |
<%= link_to 'Back', expenses_path %>

app/views/expenses/index.html.erb
<h1>Listing expenses</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Buying date</th>
      <th>Paying date</th>
      <th>Category</th>
      <th>Beneficiary</th>
      <th>Payment method</th>
			<th>Value</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @expenses.each do |expense| %>
      <tr>
        <td><%= expense.title %></td>
        <td><%= expense.buying_date %></td>
        <td><%= expense.paying_date %></td>
        <td><%= Category.find(expense.category_id).title %></td>
        <td><%= Beneficiary.find(expense.beneficiary_id).title %></td>
        <td><%= PaymentMethod.find(expense.payment_method_id).title %></td>
        <td><%= number_to_currency(expense.value / 100.0) %></td>
        <td><%= link_to 'Show', expense %></td>
        <td><%= link_to 'Edit', edit_expense_path(expense) %></td>
        <td><%= link_to 'Destroy', expense, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Expense', new_expense_path %>

app/views/expenses/new.html.erb
<h1>New expense</h1>

<%= render 'form' %>

<%= link_to 'Back', expenses_path %>

app/views/expenses/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @expense.title %>
</p>

<p>
  <strong>Buying date:</strong>
  <%= @expense.buying_date %>
</p>

<p>
  <strong>Paying date:</strong>
  <%= @expense.paying_date %>
</p>

<p>
  <strong>Category:</strong>
  <%= Category.find(@expense.category_id).title %>
</p>

<p>
  <strong>Beneficiary:</strong>
  <%= Beneficiary.find(@expense.beneficiary_id).title %>
</p>

<p>
  <strong>Payment method:</strong>
  <%= PaymentMethod.find(@expense.payment_method_id).title %>
</p>

<p>
	<strong>Value:</strong>
	<%= number_to_currency((@expense.value / 100.0)) %>
</p>
<%= link_to 'Edit', edit_expense_path(@expense) %> |
<%= link_to 'Back', expenses_path %>